print("Welcome!")
print("This is a simple welcome message.")
print("Feel free to explore and learn more about Python programming.")
print("Have a great day!")
print("Goodbye!")
print("This is the end of the welcome message.")
print("Thank you for visiting!")
print("Remember to practice coding regularly to improve your skills.")
print("Don't hesitate to ask for help if you need it.")
print("Happy coding!")
